Corrections on Auth.js
joostlawerman/vue-token pull request #1
Opened 2018-07-10 21:09 UTC by jphNovitz

This project was very useful but doesn't work for me.  I did some light changes for a good for me.  I hope this will help future users.

2018-07-16 13:06 UTC, joostlawerman requested changes
Awesome! Thank you for the additions. Could you take a look at my comment?

2018-07-16 13:06 UTC, joostlawerman commented on src/Auth.js
> +                request.headers.set('Authorization', "BEARER "+localStorage.getItem("token"));
Could you change it to `Bearer` ? It's more common

2018-07-16 17:29 UTC, jphNovitz commented
I replace BEARER to Bearer 
It's better ... more common you're right

2018-07-30 09:23 UTC, joostlawerman approved these changes

2018-07-30 09:23 UTC, merged

2018-07-30 09:40 UTC, joostlawerman commented
Hey @jphNovitz, I have released a beta version with your changes and some code style fixes you can pull it from the `beta` tag. (`[yarn|npm] [add|install] vue-token@beta`) the version should be `2.0.0-1`